sort_popular_categories:
  default: true
  description: 'If checked, the top 7 most posted in categories will appear as boxes at the top of the categories page. If not, the categories that appear in the boxes will be auto sorted by Discourse.'